### ISSUE TITLE
The problem with @font-face

### ISSUE THREAD

**Issue by loskutNat** [RobinCK/gulp-style-aliases#1]
Hi.
I have a problem. The alias from the second url in font-face doesn't work. Like this:
// input

@font-face {
    font-family:'Zawgyi-One';
    src: local('Zawgyi-One'),
    url('@aliasName/fonts/zawgyi.woff') format('woff'),
    url('@aliasName/fonts/zawgyi.ttf') format('truetype');
    font-style: normal;
    font-weight: 400;
}

// output

@font-face {
    font-family: 'Zawgyi-One';
    src: local("Zawgyi-One"),
    url("../fonts/zawgyi.woff") format("woff"),
    url("@aliasName/fonts/zawgyi.ttf") format("truetype");
    font-style: normal;
    font-weight: 400;
}

What can be wrong?

**Comment by RobinCK** [comment]
Hi.

@loskutNat please update to gulp-style-aliases@1.1.3
